[package]
name = "cloud-camp-audition"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"

[[bin]]
name = "cloud-camp"
path = "src/main.rs"